export {default as HomePage} from "./Home/index"
export {default as ProfilePage} from "./Profile/index"
export {default as LoginPage} from "./Login/index"
export {default as RegisterPage} from "./Register/index"
export {default as NotFound} from "./NotFound/index"
export {default as LivePage} from "./Live/index"
export {default as TeamPage} from "./Teams/index"
export {default as LeaderboardPage} from "./Leaderboards/index"
